language: erlang
otp_release:
  - 20.0
notifications:
  email:
    - maxim@synrc.com
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start:   always  # options: [always|never|change] default: always
install:
  - wget http://ns.synrc.com/publications/cubical
  - chmod +x cubical
  - export PATH=$PATH:$PWD
  - "./mad dep com pla bun cub"
script:
  - "./mad com"
